version: '3.4'
services:
    exabgp:
        image: mavromat/exabgp-monitor:latest
        container_name: exabgp
        restart: always
        networks:
            - artemis
        volumes:
            - ./local_configs/monitor/exabgp.conf:/home/config/exabgp.conf
