version: '3'
services:
    riperistap:
        image: inspiregroup/artemis-riperistap:${SYSTEM_VERSION}
        restart: always
        depends_on:
            - database
            - prefixtree
            - rabbitmq
            - redis
        expose:
            - 3000
        networks:
            - artemis
        environment:
            MON_TIMEOUT_LAST_BGP_UPDATE: ${MON_TIMEOUT_LAST_BGP_UPDATE}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REST_PORT: 3000
            RIS_ID: ${RIS_ID}
        volumes:
            - ./local_configs/monitor-services/riperistap/:/etc/artemis/
            - ./monitor-services/riperistap/entrypoint:/root/entrypoint
            - ./monitor-services/riperistap/core/ripe_ris.py:/root/core/ripe_ris.py
    bgpstreamlivetap:
        image: inspiregroup/artemis-bgpstreamlivetap:${SYSTEM_VERSION}
        restart: always
        depends_on:
            - database
            - prefixtree
            - rabbitmq
            - redis
        expose:
            - 3000
        networks:
            - artemis
        environment:
            MON_TIMEOUT_LAST_BGP_UPDATE: ${MON_TIMEOUT_LAST_BGP_UPDATE}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REST_PORT: 3000
        volumes:
            - ./local_configs/monitor-services/bgpstreamlivetap/:/etc/artemis/
            - ./monitor-services/bgpstreamlivetap/entrypoint:/root/entrypoint
            - ./monitor-services/bgpstreamlivetap/core/bgpstreamlive.py:/root/core/bgpstreamlive.py
    bgpstreamkafkatap:
        image: inspiregroup/artemis-bgpstreamkafkatap:${SYSTEM_VERSION}
        restart: always
        depends_on:
            - database
            - prefixtree
            - rabbitmq
            - redis
        expose:
            - 3000
        networks:
            - artemis
        environment:
            MON_TIMEOUT_LAST_BGP_UPDATE: ${MON_TIMEOUT_LAST_BGP_UPDATE}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REST_PORT: 3000
        volumes:
            - ./local_configs/monitor-services/bgpstreamkafkatap/:/etc/artemis/
            - ./monitor-services/bgpstreamkafkatap/entrypoint:/root/entrypoint
            - ./monitor-services/bgpstreamkafkatap/core/bgpstreamkafka.py:/root/core/bgpstreamkafka.py
    bgpstreamhisttap:
        image: inspiregroup/artemis-bgpstreamhisttap:${SYSTEM_VERSION}
        build: ./monitor-services/bgpstreamhisttap
        restart: always
        depends_on:
            - database
            - prefixtree
            - rabbitmq
        expose:
            - 3000
        networks:
            - artemis
        environment:
            HISTORIC: "true"
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            REST_PORT: 3000
        volumes:
            - ./local_configs/monitor-services/bgpstreamhisttap/:/etc/artemis/
            - ./monitor-services/bgpstreamhisttap/entrypoint:/root/entrypoint
            - ./monitor-services/bgpstreamhisttap/core/bgpstreamhist.py:/root/core/bgpstreamhist.py
    exabgptap:
        image: inspiregroup/artemis-exabgptap:${SYSTEM_VERSION}
        build: ./monitor-services/exabgptap
        restart: always
        depends_on:
            - database
            - prefixtree
            - rabbitmq
            - redis
        expose:
            - 3000
        networks:
            - artemis
        environment:
            MON_TIMEOUT_LAST_BGP_UPDATE: ${MON_TIMEOUT_LAST_BGP_UPDATE}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REST_PORT: 3000
        volumes:
            - ./local_configs/monitor-services/exabgptap/:/etc/artemis/
            - ./monitor-services/exabgptap/entrypoint:/root/entrypoint
            - ./monitor-services/exabgptap/core/exabgp_client.py:/root/core/exabgp_client.py
    autostarter:
        image: inspiregroup/artemis-autostarter:${SYSTEM_VERSION}
        restart: always
        depends_on:
            - bgpstreamhisttap
            - bgpstreamkafkatap
            - bgpstreamlivetap
            - database
            - detection
            - exabgptap
            - mitigation
            - notifier
            - postgres
            - prefixtree
            - configuration
            - fileobserver
            - riperistap
        networks:
            - artemis
        environment:
            AUTO_RECOVER_PROCESS_STATE: ${AUTO_RECOVER_PROCESS_STATE}
            CHECK_INTERVAL: 5
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            REST_PORT: 3000
        volumes:
            - ./local_configs/backend-services/autostarter/:/etc/artemis/
            - ./backend-services/autostarter/entrypoint:/root/entrypoint
            - ./backend-services/autostarter/core/autostarter.py:/root/core/autostarter.py
    configuration:
        image: inspiregroup/artemis-configuration:${SYSTEM_VERSION}
        restart: always
        depends_on:
            - bgpstreamhisttap
            - bgpstreamkafkatap
            - bgpstreamlivetap
            - database
            - detection
            - exabgptap
            - mitigation
            - notifier
            - postgres
            - prefixtree
            - rabbitmq
            - redis
            - riperistap
        expose:
            - 3000
        networks:
            - artemis
        environment:
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REST_PORT: 3000
        volumes:
            - ./local_configs/backend-services/configuration/:/etc/artemis/
            - ./backend-services/configuration/entrypoint:/root/entrypoint
            - ./backend-services/configuration/core/configuration.py:/root/core/configuration.py
    database:
        image: inspiregroup/artemis-database:${SYSTEM_VERSION}
        restart: always
        depends_on:
            - graphql
            - notifier
            - postgres
            - prefixtree
            - rabbitmq
            - redis
        expose:
            - 3000
        networks:
            - artemis
        environment:
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_VERSION: ${DB_VERSION}
            HASURA_HOST: ${HASURA_HOST}
            HASURA_PORT: ${HASURA_PORT}
            HASURA_GRAPHQL_ACCESS_KEY: ${HASURA_SECRET_KEY}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REST_PORT: 3000
            WITHDRAWN_HIJACK_THRESHOLD: ${WITHDRAWN_HIJACK_THRESHOLD}
            HISTORIC: ${HISTORIC}
        volumes:
            - ./local_configs/backend-services/database/:/etc/artemis/
            - ./backend-services/database/entrypoint:/root/entrypoint
            - ./backend-services/database/core/database.py:/root/core/database.py
    detection:
        image: inspiregroup/artemis-detection:${SYSTEM_VERSION}
        restart: always
        depends_on:
            - notifier
            - database
            - prefixtree
            - rabbitmq
            - redis
        expose:
            - 3000
        networks:
            - artemis
        environment:
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REST_PORT: 3000
            RPKI_VALIDATOR_ENABLED: ${RPKI_VALIDATOR_ENABLED}
            RPKI_VALIDATOR_HOST: ${RPKI_VALIDATOR_HOST}
            RPKI_VALIDATOR_PORT: ${RPKI_VALIDATOR_PORT}
        volumes:
            - ./local_configs/backend-services/detection/:/etc/artemis/
            - ./backend-services/detection/entrypoint:/root/entrypoint
            - ./backend-services/detection/core/detection.py:/root/core/detection.py
    fileobserver:
        image: inspiregroup/artemis-fileobserver:${SYSTEM_VERSION}
        restart: always
        depends_on:
            - configuration
        expose:
            - 3000
        networks:
            - artemis
        environment:
            REST_PORT: 3000
        volumes:
            - ./local_configs/backend-services/configuration/:/etc/artemis/
            - ./backend-services/fileobserver/entrypoint:/root/entrypoint
            - ./backend-services/fileobserver/core/observer.py:/root/core/observer.py
    mitigation:
        image: inspiregroup/artemis-mitigation:${SYSTEM_VERSION}
        restart: always
        depends_on:
            - rabbitmq
            - database
            - prefixtree
        expose:
            - 3000
        networks:
            - artemis
        environment:
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            REST_PORT: 3000
        volumes:
            - ./local_configs/backend-services/mitigation/:/etc/artemis/
            - ./backend-services/mitigation/entrypoint:/root/entrypoint
            - ./backend-services/mitigation/core/mitigation.py:/root/core/mitigation.py
            - ./poc_mitigate_deaggregate/poc_mitigate_deaggregate.py:/root/poc_mitigate_deaggregate.py
    notifier:
        image: inspiregroup/artemis-notifier:${SYSTEM_VERSION}
        restart: always
        depends_on:
            - rabbitmq
        expose:
            - 3000
        networks:
            - artemis
        environment:
            HIJACK_LOG_FILTER: ${HIJACK_LOG_FILTER}
            HIJACK_LOG_FIELDS: ${HIJACK_LOG_FIELDS}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            REST_PORT: 3000
        volumes:
            - ./local_configs/backend-services/notifier/:/etc/artemis/
            - ./backend-services/notifier/entrypoint:/root/entrypoint
            - ./backend-services/notifier/core/notifier.py:/root/core/notifier.py
    prefixtree:
        image: inspiregroup/artemis-prefixtree:${SYSTEM_VERSION}
        restart: always
        depends_on:
            - rabbitmq
            - redis
        expose:
            - 3000
        networks:
            - artemis
        environment:
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PORT: ${REDIS_PORT}
            REST_PORT: 3000
        volumes:
            - ./local_configs/backend-services/prefixtree/:/etc/artemis/
            - ./backend-services/prefixtree/entrypoint:/root/entrypoint
            - ./backend-services/prefixtree/core/prefixtree.py:/root/core/prefixtree.py
    redis:
        image: redis:latest
        container_name: redis
        restart: always
        networks:
            - artemis
        expose:
            - ${REDIS_PORT}
        volumes:
            - ./local_configs/backend-services/redis/redis.conf:/usr/local/etc/redis/redis.conf
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    frontend:
        image: inspiregroup/artemis-tempfrontend:${SYSTEM_VERSION}
        container_name: frontend
        restart: always
        depends_on:
            - database
            - graphql
            - postgres
            - postgrest
            - rabbitmq
        networks:
            - artemis
        expose:
            - ${WEBAPP_PORT}
        environment:
            API_HOST: ${API_HOST}
            API_PORT: ${API_PORT}
            ARTEMIS_WEB_HOST: ${ARTEMIS_WEB_HOST}
            BIND_IP: ${BIND_IP}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
            GUNICORN_WORKERS: ${GUNICORN_WORKERS:-4}
            HASURA_HOST: ${HASURA_HOST}
            HASURA_PORT: ${HASURA_PORT}
            HASURA_GRAPHQL_ACCESS_KEY: ${HASURA_SECRET_KEY}
            JS_VERSION: ${JS_VERSION}
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
            RABBITMQ_USER: ${RABBITMQ_USER}
            RABBITMQ_PASS: ${RABBITMQ_PASS}
            RABBITMQ_HOST: ${RABBITMQ_HOST}
            RABBITMQ_PORT: ${RABBITMQ_PORT}
            REST_PORT: 3000
            SECURITY_PASSWORD_SALT: ${SECURITY_PASSWORD_SALT}
            SYSTEM_VERSION: ${SYSTEM_VERSION}
            USER_ROOT_USERNAME: ${ADMIN_USER}
            USER_ROOT_PASSWORD: ${ADMIN_PASS}
            USER_ROOT_EMAIL: ${ADMIN_EMAIL}
            WEBAPP_PORT: ${WEBAPP_PORT}
        volumes:
            - ./local_configs/frontend/:/etc/artemis/
            - ./frontend/db/:/etc/webapp/db/
    nginx:
        image: nginx:1.17-alpine
        container_name: nginx
        restart: always
        depends_on:
            - frontend
            - postgrest
        networks:
            - artemis
        ports:
            # uncomment both lines for rootless
            # - "8080:8080"
            # - "8443:8443"
            # comment both lines when running rootless
            - "80:80"
            - "443:443"
        volumes:
            - ./local_configs/frontend/nginx.conf:/etc/nginx/nginx.conf
            - ./local_configs/frontend/certs/:/etc/nginx/certs/
    rabbitmq:
        image: rabbitmq:3.8.3-management-alpine
        container_name: rabbitmq
        restart: always
        networks:
            - artemis
        expose:
            - ${RABBITMQ_PORT}
            # - 15672 management port
        # ports:
        #     - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_IO_THREAD_POOL_SIZE: ${RABBITMQ_IO_THREAD_POOL_SIZE:-128}
        volumes:
            - ./other/rabbitmq/enabled-plugins:/etc/rabbitmq/enabled_plugins
    postgres:
        image: timescale/timescaledb:1.1.0-pg10
        container_name: postgres
        restart: always
        networks:
            - artemis
        expose:
            - ${DB_PORT}
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            DB_BACKUP: ${DB_BACKUP}
            DB_AUTOCLEAN: ${DB_AUTOCLEAN}
            DB_HIJACK_DORMANT: ${DB_HIJACK_DORMANT}
        volumes:
            - ./postgres-data-current:/var/lib/postgresql/data
            - ./other/postgres-entrypoint.sh:/postgres-entrypoint.sh
            - ./postgres-data-backup/:/tmp/
            - ./other/db/init.sql:/docker-entrypoint-initdb.d/zinit.sql
            - ./other/db/data/:/docker-entrypoint-initdb.d/data/
            - ./other/db/libs/:/docker-entrypoint-initdb.d/libs/
        entrypoint: ["./postgres-entrypoint.sh"]
    postgrest:
        image: postgrest/postgrest:v7.0.0
        container_name: postgrest
        restart: always
        depends_on:
            - postgres
        networks:
            - artemis
        expose:
            - ${API_PORT}
        environment:
            PGRST_DB_URI: postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?application_name=postgrest
            PGRST_DB_SCHEMA: ${DB_SCHEMA}
            PGRST_DB_ANON_ROLE: ${DB_USER}
    pg-amqp-bridge:
        image: subzerocloud/pg-amqp-bridge:0.0.6
        container_name: pg-amqp-bridge
        restart: always
        depends_on:
            - postgres
            - database
            - rabbitmq
        networks:
            - artemis
        environment:
            - POSTGRESQL_URI=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?application_name=pg-amqp-bridge
            - AMQP_URI=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}//
            - BRIDGE_CHANNELS=events:amq.direct
            # - RUST_LOG=debug
            # - RUST_BACKTRACE=1
        volumes:
            - ./backend-services/database/wait-for:/root/wait-for
        command: ["/root/wait-for", "${RABBITMQ_HOST}:${RABBITMQ_PORT}", "-t", "0", "--", "pg-amqp-bridge"]
    graphql:
        image: hasura/graphql-engine:v1.1.0
        container_name: graphql
        restart: always
        depends_on:
            - postgres
        networks:
            - artemis
        expose:
            - ${HASURA_PORT}
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?application_name=graphql
            HASURA_GRAPHQL_ACCESS_KEY: ${HASURA_SECRET_KEY}
            HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GUI}
            HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key":"${JWT_SECRET_KEY}"}'
        command:
            - graphql-engine
            - serve

networks:
    artemis:
